# .github/workflows/ci-cd.yml
name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) Faz checkout do repositório
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2) Configura JDK 11
      - name: Configurar JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'ant'

      # 3) (Opcional) Confirma que a pasta lib/ existe e contém os JARs
      - name: Verificar diretório lib/ e JARs
        run: |
          if [ ! -d "lib" ]; then
            echo "ERRO: diretório lib/ não encontrado." >&2
            exit 1
          fi
          if [ ! -f "lib/postgresql-42.7.3.jar" ]; then
            echo "ERRO: driver PostgreSQL não encontrado em lib/." >&2
            exit 1
          fi
          if [ ! -f "lib/junit-platform-console-standalone-1.9.2.jar" ]; then
            echo "ERRO: JUnit Platform Console Standalone não encontrado em lib/." >&2
            exit 1
          fi
          echo "✔ Todos os JARs necessários estão em lib/"

      # 4) Exibe a versão do Ant (já instalado no ubuntu-latest)
      - name: Verificar versão do Ant
        run: ant -version

      # 5) Executa Ant na target “test” (compila e roda todos os testes)
      - name: Executar Ant → test
        run: ant test

      # 6) (Opcional) Para gerar o JAR final, descomente abaixo:
      # - name: Empacotar JAR final
      #   run: ant jar

      # 7) (Opcional) Publicar artifact ou fazer upload do JAR, caso queira usar em outra ação:
      # - name: Upload do JAR
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: TryTasks-JAR
      #     path: dist/TryTasks.jar
